export default {
  CLASS_NONE: 'CLASS_NONE',
  CLASS_WARRIOR: 'CLASS_WARRIOR',
  CLASS_PALADIN: 'CLASS_PALADIN',
  CLASS_HUNTER: 'CLASS_HUNTER',
  CLASS_ROGUE: 'CLASS_ROGUE',
  CLASS_PRIEST: 'CLASS_PRIEST',
  CLASS_DEATH_KNIGHT: 'CLASS_DEATH_KNIGHT',
  CLASS_SHAMAN: 'CLASS_SHAMAN',
  CLASS_MAGE: 'CLASS_MAGE',
  CLASS_WARLOCK: 'CLASS_WARLOCK',
  CLASS_MONK: 'CLASS_MONK',
  CLASS_DRUID: 'CLASS_DRUID',
  CLASS_DEMON_HUNTER: 'CLASS_DEMON_HUNTER'
}
